name: Build Flatpak

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  flatpak:
    name: "Build Flatpak Bundle"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Flatpak
        run: |
          flatpak-builder --repo=repo --force-clean build-dir flatpak/com.github.grab_ui.yml
          flatpak build-bundle repo grab-ui.flatpak com.github.grab_ui

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: grab-ui-flatpak
          path: grab-ui.flatpak
